// Export all admin components for easier imports
export { default as Table } from "./Table";
export { default as Modal } from "./Modal";
export { default as FormField } from "./FormField";
export { default as SearchFilter } from "./SearchFilter";
export { default as StatCard } from "./StatCard";
export { default as ActionButtons } from "./ActionButtons";
export { default as PageHeader } from "./PageHeader";
export { default as AdminHeader } from "./AdminHeader";
